import React from "react";
import {useAppStore} from "../../hooks/useAppStore";
import {PageHeader,Section,Priority,Status} from "../../components/ui/Components";
const config={
 engg:{dept:"Engineering",title:"Engineering Planning Workspace",desc:"Prioritize track/P-Way demand and prepare possession-ready work.",cols:["Registered","Validated","Prioritized","Window Proposed","Plan Proposed"]},
 trd:{dept:"TRD",title:"Traction & Power Block Planning",desc:"Prepare OHE work, isolation requirements and power-block proposals.",cols:["Registered","Validated","Prioritized","Window Proposed","Plan Proposed"]},
 snt:{dept:"S&T",title:"S&T Disconnection Planning",desc:"Prepare signal/telecom work, disconnections, testing and restoration windows.",cols:["Registered","Validated","Prioritized","Window Proposed","Plan Proposed"]},
 field:{dept:null,title:"Today's Possessions",desc:"Field-facing view of published and executing work only.",cols:["Published","Executing","Completion Submitted"]},
 admin:{dept:null,title:"Planning Oversight",desc:"Read-only governance view across departmental planning states.",cols:["Prioritized","Window Proposed","Bundled","Plan Proposed","Approved"]}
};
export default function DepartmentPlanning({role}){const{works}=useAppStore();const c=config[role]||config.admin;const own=c.dept?works.filter(w=>w.dept===c.dept):works;return <div className="content"><PageHeader eyebrow={`${(c.dept||"SYSTEM").toUpperCase()} · PLANNING`} title={c.title} description={c.desc}/><Section title="Planning board"><div className="kanban">{c.cols.map(s=><div className="kanban-col" key={s}><h3>{s}<span>{own.filter(w=>w.status===s).length}</span></h3>{own.filter(w=>w.status===s).map(w=><div className="kanban-card" key={w.id}><b>{w.id}</b><strong>{w.title}</strong><small>{w.section} · {w.duration} min · {w.dept}</small><Priority>{w.criticality}</Priority></div>)}</div>)}</div></Section><Section title={role==="field"?"Field rules":role==="admin"?"Governance rules":"Department planning rules"}><div className="rules"><div><b>1</b><span>{role==="field"?"Only published work can be started in the field.":"Critical safety work stays ahead of routine demand."}</span></div><div><b>2</b><span>{role==="admin"?"Administration observes workflow; it does not approve operational blocks.":"Dependencies and safety prerequisites must be explicit."}</span></div><div><b>3</b><span>{role==="field"?"Completion requires evidence and supervisor verification.":"A department proposal is not an approved railway block."}</span></div></div></Section></div>}
