import React from "react";
import {NavLink,Outlet,useNavigate} from "react-router-dom";
import {LayoutDashboard,ClipboardList,PlusCircle,CalendarDays,Layers3,ShieldCheck,CheckCircle2,BarChart3,Users,LogOut,TrainFront,Database,GitMerge,FileCheck2,Map,HardHat,Settings,Activity,Clock3} from "lucide-react";
import {ROLES} from "../../data/mockData";
import ErrorBoundary from "../ui/ErrorBoundary";
const navs={
admin:[["dashboard","Command Dashboard",LayoutDashboard],["work-bank","All Work & Data",Database],["register-work","Register / Import Work",PlusCircle],["planning","Planning Oversight",CalendarDays],["candidate-windows","Window Library",Layers3],["safety-review","Safety Governance",ShieldCheck],["execution","Execution Oversight",Activity],["completion-verification","Closure Audit",FileCheck2],["analytics","System Analytics",BarChart3],["admin","Users & Configuration",Users]],
engg:[["dashboard","Engineering Control Board",LayoutDashboard],["work-bank","Track Work Bank",ClipboardList],["register-work","Track Work Registration",PlusCircle],["planning","Engineering Planning",CalendarDays],["candidate-windows","Track Windows",Layers3],["safety-review","Engineering Safety",ShieldCheck],["execution","Field Follow-up",HardHat],["analytics","Engineering Analytics",BarChart3]],
trd:[["dashboard","TRD Control Board",LayoutDashboard],["work-bank","OHE Work Bank",ClipboardList],["register-work","TRD Work Registration",PlusCircle],["planning","Traction Planning",CalendarDays],["candidate-windows","Power Block Windows",Layers3],["safety-review","Isolation & Safety",ShieldCheck],["execution","OHE Execution",HardHat],["analytics","TRD Analytics",BarChart3]],
snt:[["dashboard","S&T Control Board",LayoutDashboard],["work-bank","S&T Work Bank",ClipboardList],["register-work","S&T Work Registration",PlusCircle],["planning","S&T Planning",CalendarDays],["candidate-windows","Disconnection Windows",Layers3],["safety-review","S&T Safety",ShieldCheck],["execution","S&T Execution",HardHat],["analytics","S&T Analytics",BarChart3]],
control:[["dashboard","Operations Control Center",LayoutDashboard],["work-bank","Network Work Bank",ClipboardList],["register-work","Work Intake",PlusCircle],["planning","Integrated Block Planner",GitMerge],["candidate-windows","Candidate Window Engine",Layers3],["safety-review","Safety & Conflict Gate",ShieldCheck],["approvals","Approval Inbox",FileCheck2],["execution","Live Block Execution",Activity],["completion-verification","Completion Verification",CheckCircle2],["analytics","Operations Analytics",BarChart3]],
field:[["dashboard","Field Operations Board",LayoutDashboard],["work-bank","Assigned Work",ClipboardList],["register-work","Field Issue / Work Request",PlusCircle],["planning","Today's Possessions",Clock3],["candidate-windows","Available Windows",Layers3],["safety-review","Pre-Work Safety",ShieldCheck],["execution","Execution & Evidence",HardHat],["completion-verification","My Submissions",FileCheck2],["analytics","Field Performance",BarChart3]]
};
export default function AppShell({role}){const r=ROLES[role],nav=useNavigate();return <div className="shell"><aside className="sidebar"><div className="brand"><TrainFront/><div><b>RAILPLAN</b><small>SIH26027</small></div></div><div className="role-chip"><span>ACTIVE ROLE</span><strong>{r.label}</strong><small>{r.unit}</small></div><nav>{navs[role].map(([slug,label,Icon])=><NavLink key={slug} to={r.base+"/"+slug} className={({isActive})=>isActive?"active":""}><Icon size={17}/>{label}</NavLink>)}</nav><div className="sidebar-foot"><button onClick={()=>{try{localStorage.removeItem("railplan_role")}catch{};nav("/login")}}><LogOut size={17}/> Sign out</button><small>RailPlan SIH26027 · Node.js + ML API</small></div></aside><main className="main"><header className="topbar"><div className="mobile-title"><b>{r.label}</b><small>{r.unit}</small></div><div className="top-actions"><button><Map size={17}/></button><button><Settings size={17}/></button><div className="user-avatar">{r.label[0]}</div></div></header><ErrorBoundary><Outlet/></ErrorBoundary></main></div>}
