import React,{useState} from "react"; import {useNavigate,Link} from "react-router-dom"; import {TrainFront,ShieldCheck,ArrowRight} from "lucide-react"; import {ROLES} from "../../data/mockData";
import {removeStorage} from "../../utils/storage";
import {api} from "../../api/client";
export default function Login(){const nav=useNavigate();const [role,setRole]=useState("engg");const [busy,setBusy]=useState(false);
const submit=async e=>{e.preventDefault();setBusy(true);try{const result=await api.login(role);localStorage.setItem("railplan_role",result.user.role);localStorage.setItem("railplan_user",result.user.id);localStorage.setItem("railplan_token",result.access_token);nav(ROLES[role].base+"/dashboard")}catch(err){console.error(err);alert(err.message || 'Unable to connect to backend. Start the Node.js backend and ML service first.')}finally{setBusy(false)}};
return <div className="login-page"><div className="login-brand"><div className="logo"><TrainFront/></div><div><b>RAILPLAN</b><span>AI-POWERED AUTOMATIC BLOCK PLANNING · SIH26027</span></div></div>
<div className="login-card"><div className="login-copy"><span className="eyebrow">SECURE OPERATIONS WORKSPACE</span><h1>Sign in to RailPlan</h1><p>Role-aware planning, approval and field execution prototype for railway maintenance blocks.</p></div>
<div className="role-grid">{Object.entries(ROLES).map(([k,v])=><button className={"role-card "+(role===k?"selected":"")} onClick={()=>setRole(k)} key={k}><div className="role-icon">{v.label[0]}</div><div><strong>{v.label}</strong><span>{v.unit}</span></div><span className="radio">{role===k?"✓":""}</span></button>)}</div>
<form onSubmit={submit}><label>Demo identity<input defaultValue={ROLES[role].label+" · Demo User"} readOnly/></label><button className="primary" disabled={busy}>{busy?"Opening workspace":"Continue to workspace"} <ArrowRight size={17}/></button></form>
<div className="login-note"><ShieldCheck size={15}/> Connected mode · Node.js + ML API + database + optimizer</div><button type="button" className="manual-link" onClick={()=>{removeStorage("railplan-demo-v3");removeStorage("railplan-demo-v7");alert("Demo data reset. Sample data will reload on the next workspace visit.")}}>Reset sample data</button><Link className="manual-link" to="/manual">Open User Manual →</Link></div><div className="login-footer">SIH26027 · Ministry of Railways · Decision-support prototype</div></div>}
