import React from "react";import{Link}from"react-router-dom";import{TrainFront,ArrowLeft}from"lucide-react";
const roles=[
["Engineering Planner","Register track/P-Way defects → validate and prioritize → propose track windows → send possession-ready work for integrated planning → follow field completion."],
["TRD Planner","Register OHE/traction work → define isolation and earthing needs → propose power-block windows → coordinate shared possessions → monitor OHE restoration."],
["S&T Planner","Register signal/telecom work → define disconnection/interlocking needs → propose S&T windows → plan testing/restoration → monitor completion."],
["Control / Senior Engineer","Review network demand → generate/bundle candidate blocks → check train conflicts and safety → approve/publish → monitor execution → verify completion."],
["Field User","View assigned published work → complete pre-work safety → start execution → record actual work/evidence → submit completion for verification."],
["System Administrator","Manage demo users/roles, configuration, data-source readiness and audit/analytics. Admin does not replace operational approval authority."]];
export default function UserManual(){return <div className="manual-page"><div className="manual-wrap"><div className="manual-head"><TrainFront/><div><span>RAILPLAN · SIH26027</span><h1>User Manual</h1><p>Frontend prototype workflow and role access guide.</p></div></div><section><h2>How to use the prototype</h2><ol><li>Open Login and select the role you want to demonstrate.</li><li>Each role opens its own navigation and operational workspace.</li><li>All data is sample data stored locally in your browser; no database or backend is used.</li><li>Use Register Work to create demo work, then open its detail screen to advance permitted lifecycle states.</li><li>Control demonstrates integrated planning, safety/conflict review and approval. Field demonstrates execution and evidence.</li></ol></section><section><h2>Role workflows</h2><div className="manual-roles">{roles.map(([a,b])=><div><h3>{a}</h3><p>{b}</p></div>)}</div></section><section><h2>Lifecycle</h2><p className="manual-flow">Registered → Validated → Prioritized → Window Proposed → Bundled → Plan Proposed → Approved → Published → Executing → Completion Submitted → Verified → Closed</p></section><section><h2>Prototype data</h2><p>TMS, SMMS, TDMS and COA labels are represented only as sample frontend datasets/readiness indicators. This package does not connect to Indian Railways systems, Supabase, SQL, REST APIs or any external database.</p></section><Link className="btn" to="/login"><ArrowLeft size={16}/> Back to login</Link></div></div>}
